services:
  discovery:
    build:
      context: ./discovery_service
    container_name: discovery_service
    ports:
      - "8761:8761"
    networks:
      - movie-net

  postgres:
    image: postgres:17-alpine
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movie-net

  reservation:
    build:
      context: ./reservation-service
    container_name: reservation_service
    depends_on:
      - discovery
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: root
      DB_PASSWORD: mypassword
    ports:
      - "8082:8082"
    networks:
      - movie-net

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    depends_on:
      - discovery
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: root
      DB_PASSWORD: mypassword
    ports:
      - "8081:8081"
    networks:
      - movie-net

volumes:
  pgdata:


networks:
  movie-net:
    driver: bridge
