

services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/18/docker

volumes:
  pgdata: